doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Page:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/Page'
                prefix: App\Infrastructure\Entity\Page
                alias: Page

            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/User'
                prefix: App\Infrastructure\Entity\User
                alias: User

            Contact:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/Contact'
                prefix: App\Infrastructure\Entity\Contact
                alias: Contact

            Gallery:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/Gallery'
                prefix: App\Infrastructure\Entity\Gallery
                alias: Gallery

            Project:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/Project'
                prefix: App\Infrastructure\Entity\Project
                alias: Project

            Styles:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/Styles'
                prefix: App\Infrastructure\Entity\Styles
                alias: Styles

            Footer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entity/Footer'
                prefix: App\Infrastructure\Entity\Footer
                alias: Footer

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
