nelmio_api_doc:
    documentation:
        info:
            title: Content Administration API
            description: Powered by Przemysław Tarapacki
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
