version: "3.4"

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www/cms-manager-api
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - php-fpm
      - database

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - '.:/var/www/cms-manager-api'
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal
    environment:
      APP_ENV: ${APP_ENV}
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG: ${XDEBUG}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-cmsmanager}?serverVersion=${POSTGRES_VERSION:-14}

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cmsmanager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - internal

  mercure:
    image: dunglas/mercure
    environment:
      # Uncomment the following line to disable HTTPS,
      # SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - internal

volumes:
  db-data:
  mercure_data:
  mercure_config:

networks:
  internal:
    driver: bridge
